name: Backend CI - Node.js

# Se ejecuta al integrar código a la rama 'main' (Pull Requests y Merges/Pushes)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # TAREA 1: Instalación y Validación (Build)
  build:
    name: Build & Install
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # Usa la versión mayor 22 para compatibilidad
          cache: 'npm' # Acelera futuras ejecuciones guardando las dependencias

      - name: Instalar dependencias limpias
        # npm ci es mejor para pipelines que npm install porque respeta estrictamente el package-lock.json
        run: npm ci 

  # TAREA 2: Pruebas (Test)
  test:
    name: Run Tests
    needs: build # Obliga a que el Build termine con éxito antes de probar
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Instalar dependencias limpias
        run: npm ci

      - name: Ejecutar pruebas
        # NOTA: Esto fallará hasta que configures un framework de pruebas en tu package.json
        run: npm test